CREATE TABLE ETUDIANT
(
  ID     INTEGER AUTO_INCREMENT,
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE PROFESSEUR
(
  ID     INTEGER,
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255),
  PRIMARY KEY (ID)
);


CREATE TABLE MATIERE
(
  ID  INTEGER,
  NOM VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE COURS
(
  ID            INTEGER,
  ID_MATIERE    INTEGER,
  ID_PROFESSEUR INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE (ID),
  FOREIGN KEY (ID_PROFESSEUR) REFERENCES MATIERE (ID)
);

CREATE TABLE SUIT_COURS
(
  ID       INTEGER,
  ID_COURS INTEGER,
  ID_ELEVE INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE (ID),
  FOREIGN KEY (ID_PROFESSEUR) REFERENCES MATIERE (ID)
);

