CREATE TABLE ETUDIANT
(
  ID     INTEGER AUTO_INCREMENT,
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE PROFESSEUR
(
  ID     INTEGER AUTO_INCREMENT,
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255),
  PRIMARY KEY (ID)
);


CREATE TABLE MATIERE
(
  ID  INTEGER AUTO_INCREMENT,
  NOM VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE COURS
(
  ID            INTEGER AUTO_INCREMENT,
  ID_MATIERE    INTEGER,
  ID_PROFESSEUR INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE (ID),
  FOREIGN KEY (ID_PROFESSEUR) REFERENCES PROFESSEUR (ID)
);

CREATE TABLE SUIT_COURS
(
  ID       INTEGER AUTO_INCREMENT,
  ID_COURS INTEGER,
  ID_ETUDIANT INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_COURS) REFERENCES COURS (ID),
  FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID)
);

