CREATE TABLE ADRESSE
(
  ID      INTEGER AUTO_INCREMENT,
  VILLE   VARCHAR(255),
  DISTANCE      INTEGER(255),
  PRIMARY KEY (ID)
);

CREATE TABLE RESPONSABLE
(
  ID     INTEGER AUTO_INCREMENT,
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255),
  ID_ETUDIANT INTEGER,
  FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID),
  PRIMARY KEY (ID)
);

ALTER TABLE ETUDIANT
ADD ID_ADRESSE INTEGER;

ALTER TABLE ETUDIANT
ADD FOREIGN KEY (ID_ADRESSE) REFERENCES ADRESSE (ID);

INSERT INTO ADRESSE(VILLE,DISTANCE) VALUES ('Guildford', 10);
INSERT INTO ADRESSE(VILLE,DISTANCE) VALUES ('London', 50);

UPDATE ETUDIANT SET ID_ADRESSE = 1 where ID =1;
UPDATE ETUDIANT SET ID_ADRESSE = 2 where ID =3;

INSERT INTO RESPONSABLE(NOM,PRENOM,ID_ETUDIANT) VALUES ('Jagger','Mick',1);
INSERT INTO RESPONSABLE(NOM,PRENOM,ID_ETUDIANT) VALUES ('Watts','Charlie',1);
INSERT INTO RESPONSABLE(NOM,PRENOM,ID_ETUDIANT) VALUES ('Grohl', 'Dave',2);